### ISSUE TITLE
Create github release

### ISSUE THREAD

**Issue by svrana** [333fred/i3-ratiosplit#1]
Thank you for your work on this! 

Would you remind creating a release? I'd like to package it for nixos if that's ok with you and having a (source) release will make it a bit easier.

**Comment by 333fred** [comment]
Sure, I created https://github.com/333fred/i3-ratiosplit/releases/tag/v0.1.0. LMK if you need anything else.

**Comment by svrana** [comment]
Ooops, there is one other thing. You mind throwing a LICENSE in there? or documenting which license you're using in the README?

**Comment by 333fred** [comment]
Done.
